apiVersion: v1
name: redis-twemproxy
version: 0.4.0
appVersion: 6.0.10
description: Twemproxy Cluster
icon: https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Redis_Logo.svg/1200px-Redis_Logo.svg.png
keywords:
  - redis
  - twmeproxy
maintainers:
- email: yuriyku@icloud.com
  name: yuriyku
