{{- if .Values.auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keydb-cluster.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  auth: {{ .Values.auth | b64enc | quote }}
{{- end -}}
