---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- toYaml .Values.redis.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ template "fullname" . }}
  podManagementPolicy: Parallel
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.redis.replicaCount }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ template "fullname" . }}
      annotations:
      {{- toYaml .Values.redis.annotations | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.twemproxy.terminationGracePeriodSeconds }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: conf
          configMap:
            name: {{ template "fullname" . }}-configmap
            defaultMode: 0755 
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - image: jcbarrales/redis_exporter
        imagePullPolicy: Always
        name: redis-exporter
        ports:
        - containerPort: {{ .Values.redis.exporter.port }}
          protocol: TCP
        resources: 
        {{- toYaml .Values.redis.exporter.resources | nindent 10 }}
      - name: redis
        image: {{ .Values.redis.image }}
        command: ["redis-server", "/conf/redis.conf"]
        securityContext:
          runAsUser: 0             
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false      
        livenessProbe:
        {{- toYaml .Values.redis.livenessProbe | nindent 10 }}
        readinessProbe:
        {{- toYaml .Values.redis.readinessProbe | nindent 10 }}     
        resources: 
        {{- toYaml .Values.redis.resources | nindent 10 }}
        ports:
        - name: {{ template "fullname" . }}
          containerPort: 6379